export const siteConfig = {
  name: 'Sylvie',
  tagline: 'Your AI-Powered Second Brain',
  url: 'https://sylvie.app',
  ogImage: 'https://sylvie.app/og.png',
  description:
    'Sylvie is an intelligent note-taking app that thinks with you. Capture thoughts, organize ideas effortlessly, and let AI help you connect the dots. Transform scattered notes into actionable insights with smart search, automatic tagging, and contextual suggestions.',
  shortDescription:
    'AI-powered note-taking that helps you think better. Smart organization, instant search, and contextual insights.',
  keywords: [
    'AI note taking',
    'smart notes',
    'second brain',
    'knowledge management',
    'AI-powered notes',
    'intelligent note-taking',
    'note organization',
    'digital notes',
    'productivity app',
    'note search',
    'automatic tagging',
    'AI writing assistant',
    'personal knowledge base',
    'note management',
    'smart note app',
  ],
  features: [
    'AI-powered organization',
    'Smart search & discovery',
    'Automatic tagging',
    'Contextual suggestions',
    'Cross-note connections',
    'Voice to text',
    'Rich text editing',
    'Secure & private',
  ],
  authors: [
    {
      name: 'Yash Gourav Kar',
      url: 'https://dub.sh/yashk',
      twitter: '@YashGouravKar1',
    },
  ],
  creator: 'Yash Gourav Kar',
  links: {
    x: 'https://x.com/YashGouravKar1',
    github: 'https://git.new/ygkr',
    githubAccount: 'https://github.com/99Yash',
    web: 'https://dub.sh/yashk',
    linkedin: 'https://dub.sh/lnkedin',
    mail: 'yashgouravkar@gmail.com',
  },
};
